"""Generate this deployment's credentials, once, on first boot.

Run as a one-shot container by ``deploy/docker-compose.yaml``, before anything that
needs a credential::

    python -m app.bootstrap_secrets

Three files land in the directory named by ``METALMARK_SECRETS_DIR`` (``/secrets``
by default), each one a credential that has to exist before the stack can start:

===================== ==========================================================
``metalmark_secret_key``  the Fernet key — it is what encrypts household bank
                          credentials at rest (ARCHITECTURE §5)
``postgres_password``     the Postgres owner role, used to migrate
``app_db_password``       the RLS-bound application role, used at runtime
===================== ==========================================================

A deployment that ships a default for any of these is a deployment whose
credentials are in a git repository — the accident ``scripts/secret_scan.sh``
exists to prevent. Generating them at install time is what lets the compose file
carry none at all, and it is the difference between an install that is one
command and an install that is a command plus a file you are told to go and
write somewhere.

**Nothing here is ever overwritten.** The Fernet key decrypts what is already in
the database, so regenerating it would not rotate anything: it would make every
stored credential undecryptable, and the failure would surface later and
somewhere else (the next sync, not this command). An existing file is left
exactly as it is, which makes a restart a no-op and makes deleting the volume the
only way to get a new key — deliberate and loud, rather than a race.

The values are never printed. The output is a line per file saying whether this
run was the one that made it, which is what an install log should say and is all
it should say.
"""

from __future__ import annotations

import os
import secrets
import sys
from pathlib import Path

from cryptography.fernet import Fernet

#: Default matches the volume mount in deploy/docker-compose.yaml.
SECRETS_DIR = Path(os.environ.get("METALMARK_SECRETS_DIR", "/secrets"))

#: The Fernet key is generated by the library that consumes it rather than by
#: `openssl rand` in a shell, so the key is valid for that library by
#: construction rather than by a base64 alphabet happening to line up.
#:
#: The two passwords are `token_urlsafe`, which is alphanumerics plus `-` and
#: `_` — every character of it safe in the DSN built by `Settings._dsn`, and none
#: of them a quote, which matters because migration 0001 interpolates the app
#: password into a `CREATE ROLE ... PASSWORD '...'` statement.
GENERATORS = {
    "metalmark_secret_key": lambda: Fernet.generate_key().decode(),
    "postgres_password": lambda: secrets.token_urlsafe(32),
    "app_db_password": lambda: secrets.token_urlsafe(32),
}

#: Readable only by the owner (the app containers run as root and this is the key
#: to the household's bank credentials), **except** for the Postgres owner's
#: password, which the database container has to read as uid 999 and cannot if
#: this is 0600. 0644 is also the mode docker swarm gives a mounted secret, so
#: this is the conventional answer rather than a compromise invented here.
MODES = {
    "metalmark_secret_key": 0o600,
    "postgres_password": 0o644,
    "app_db_password": 0o600,
}


def generate(directory: Path = SECRETS_DIR) -> dict[str, bool]:
    """Write any missing credential. Returns ``{name: created}``.

    Idempotent by design and not merely in effect: an existing file is read but
    never rewritten, so running this twice cannot change a key, and a deployment
    that restarts is not a deployment that rotates.
    """
    directory.mkdir(parents=True, exist_ok=True)
    created: dict[str, bool] = {}
    for name, make in GENERATORS.items():
        path = directory / name
        if path.exists():
            created[name] = False
            continue
        # O_EXCL rather than a bare write: if two containers ever raced here, the
        # loser must fail loudly instead of overwriting a key that the winner has
        # already handed to the database.
        fd = os.open(path, os.O_WRONLY | os.O_CREAT | os.O_EXCL, MODES[name])
        try:
            os.write(fd, make().encode())
        finally:
            os.close(fd)
        # O_CREAT's mode is masked by the umask, and a umask only ever removes
        # bits — so the file is never more readable than MODES says, at any
        # moment, and this line only repairs a mode that came out *stricter*.
        os.chmod(path, MODES[name])
        created[name] = True
    return created


def main() -> int:
    try:
        created = generate()
    except FileExistsError:  # pragma: no cover - a racing second container
        print("bootstrap_secrets: another container is generating these", file=sys.stderr)
        return 1
    except OSError as exc:
        print(f"bootstrap_secrets: cannot write to {SECRETS_DIR}: {exc}", file=sys.stderr)
        return 1

    for name, was_created in created.items():
        verb = "generated" if was_created else "already present"
        print(f"bootstrap_secrets: {name} {verb}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
